<?php

namespace PaymentAssist;

use PaymentAssist\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class CreditsafeClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('CT_demographicsidentity', Type\CTDemographicsidentity::class),
            new ClassMap('CT_demographicsperson', Type\CTDemographicsperson::class),
            new ClassMap('CT_demographicsaccommodation', Type\CTDemographicsaccommodation::class),
            new ClassMap('CT_demographicsemail', Type\CTDemographicsemail::class),
            new ClassMap('CT_demographicstelephone', Type\CTDemographicstelephone::class),
            new ClassMap('CT_demographicsincome', Type\CTDemographicsincome::class),
            new ClassMap('CT_demographicsexpenditure', Type\CTDemographicsexpenditure::class),
            new ClassMap('CT_demographicsaccount', Type\CTDemographicsaccount::class),
            new ClassMap('CT_demographicsemployment', Type\CTDemographicsemployment::class),
            new ClassMap('CT_demographicsincomedetails', Type\CTDemographicsincomedetails::class),
            new ClassMap('CT_applicantdemographics', Type\CTApplicantdemographics::class),
            new ClassMap('contact', Type\Contact::class),
            new ClassMap('CT_address', Type\CTAddress::class),
            new ClassMap('CT_inputaddress', Type\CTInputaddress::class),
            new ClassMap('CT_inputname', Type\CTInputname::class),
            new ClassMap('CT_inputamendment', Type\CTInputamendment::class),
            new ClassMap('CT_amendsubsequent', Type\CTAmendsubsequent::class),
            new ClassMap('amendments', Type\Amendments::class),
            new ClassMap('CT_searchapplicant', Type\CTSearchapplicant::class),
            new ClassMap('CT_searchrequest', Type\CTSearchrequest::class),
            new ClassMap('CT_inputaddressandmatches', Type\CTInputaddressandmatches::class),
            new ClassMap('fullmatches', Type\Fullmatches::class),
            new ClassMap('fullmatch', Type\Fullmatch::class),
            new ClassMap('addressmatch', Type\Addressmatch::class),
            new ClassMap('name', Type\Name::class),
            new ClassMap('namematches', Type\Namematches::class),
            new ClassMap('namematch', Type\Namematch::class),
            new ClassMap('CT_picklistapplicant', Type\CTPicklistapplicant::class),
            new ClassMap('CT_linkrequest', Type\CTLinkrequest::class),
            new ClassMap('CT_jobdetails', Type\CTJobdetails::class),
            new ClassMap('CT_payload', Type\CTPayload::class),
            new ClassMap('CT_apipicklist', Type\CTApipicklist::class),
            new ClassMap('CT_Search', Type\CTSearch::class),
            new ClassMap('CT_SearchDefinition', Type\CTSearchDefinition::class),
            new ClassMap('CT_SubsequentSearch', Type\CTSubsequentSearch::class),
            new ClassMap('CT_SubsequentSearchDefinition', Type\CTSubsequentSearchDefinition::class),
            new ClassMap('CT_LinkSearch', Type\CTLinkSearch::class),
            new ClassMap('CT_LinkSearchDefinition', Type\CTLinkSearchDefinition::class),
            new ClassMap('CT_LookupDataResponse', Type\CTLookupDataResponse::class),
            new ClassMap('CT_LookupDataResult', Type\CTLookupDataResult::class),
            new ClassMap('table', Type\Table::class),
            new ClassMap('row', Type\Row::class),
            new ClassMap('CT_TestResponse', Type\CTTestResponse::class),
            new ClassMap('CT_TestResult', Type\CTTestResult::class),
            new ClassMap('callcreditheaders', Type\Callcreditheaders::class),
            new ClassMap('CT_outputaddress', Type\CTOutputaddress::class),
            new ClassMap('CT_outputerhistory', Type\CTOutputerhistory::class),
            new ClassMap('CT_outputscore', Type\CTOutputscore::class),
            new ClassMap('score', Type\Score::class),
            new ClassMap('reasons', Type\Reasons::class),
            new ClassMap('CT_outputaddressconf', Type\CTOutputaddressconf::class),
            new ClassMap('CT_outputjudgment', Type\CTOutputjudgment::class),
            new ClassMap('CT_outputinsolvency', Type\CTOutputinsolvency::class),
            new ClassMap('restriction', Type\Restriction::class),
            new ClassMap('CT_outputsearchhistory', Type\CTOutputsearchhistory::class),
            new ClassMap('CT_outputlinkaddresses', Type\CTOutputlinkaddresses::class),
            new ClassMap('CT_outputlinkaddress', Type\CTOutputlinkaddress::class),
            new ClassMap('CT_outputaddresslinks', Type\CTOutputaddresslinks::class),
            new ClassMap('CT_outputaddresslink', Type\CTOutputaddresslink::class),
            new ClassMap('CT_outputcifasfiling', Type\CTOutputcifasfiling::class),
            new ClassMap('details', Type\Details::class),
            new ClassMap('CT_outputcifasaddress', Type\CTOutputcifasaddress::class),
            new ClassMap('CT_outputcifassubject', Type\CTOutputcifassubject::class),
            new ClassMap('person', Type\Person::class),
            new ClassMap('company', Type\Company::class),
            new ClassMap('CT_outputcifascasedata', Type\CTOutputcifascasedata::class),
            new ClassMap('filingreasons', Type\Filingreasons::class),
            new ClassMap('subjects', Type\Subjects::class),
            new ClassMap('CT_outputcifascase', Type\CTOutputcifascase::class),
            new ClassMap('dmrs', Type\Dmrs::class),
            new ClassMap('CT_outputshareaccount', Type\CTOutputshareaccount::class),
            new ClassMap('supplierdetails', Type\Supplierdetails::class),
            new ClassMap('accholderdetails', Type\Accholderdetails::class),
            new ClassMap('default', Type\DefaultType::class),
            new ClassMap('delinquent', Type\Delinquent::class),
            new ClassMap('acchistory', Type\Acchistory::class),
            new ClassMap('ah', Type\Ah::class),
            new ClassMap('accdetails', Type\Accdetails::class),
            new ClassMap('CT_outputdemographics', Type\CTOutputdemographics::class),
            new ClassMap('family', Type\Family::class),
            new ClassMap('household', Type\Household::class),
            new ClassMap('economicactivity', Type\Economicactivity::class),
            new ClassMap('socialclass', Type\Socialclass::class),
            new ClassMap('housing', Type\Housing::class),
            new ClassMap('propertyprice', Type\Propertyprice::class),
            new ClassMap('movement', Type\Movement::class),
            new ClassMap('CT_outputdemographics2006', Type\CTOutputdemographics2006::class),
            new ClassMap('age', Type\Age::class),
            new ClassMap('tenure', Type\Tenure::class),
            new ClassMap('hhcomp', Type\Hhcomp::class),
            new ClassMap('economic', Type\Economic::class),
            new ClassMap('lifestage', Type\Lifestage::class),
            new ClassMap('social', Type\Social::class),
            new ClassMap('occupation', Type\Occupation::class),
            new ClassMap('mortgage', Type\Mortgage::class),
            new ClassMap('sharehld', Type\Sharehld::class),
            new ClassMap('unemployment', Type\Unemployment::class),
            new ClassMap('unemprate', Type\Unemprate::class),
            new ClassMap('property', Type\Property::class),
            new ClassMap('international', Type\International::class),
            new ClassMap('CT_outputsummaryblock', Type\CTOutputsummaryblock::class),
            new ClassMap('CT_alertsummary', Type\CTAlertsummary::class),
            new ClassMap('CT_hhosummary', Type\CTHhosummary::class),
            new ClassMap('CT_summarysearches', Type\CTSummarysearches::class),
            new ClassMap('CT_summarybai', Type\CTSummarybai::class),
            new ClassMap('CT_summaryjudgment', Type\CTSummaryjudgment::class),
            new ClassMap('CT_summarynotices', Type\CTSummarynotices::class),
            new ClassMap('CT_summarylinks', Type\CTSummarylinks::class),
            new ClassMap('CT_summarycifas', Type\CTSummarycifas::class),
            new ClassMap('CT_summaryshare', Type\CTSummaryshare::class),
            new ClassMap('CT_alertsummaryshare', Type\CTAlertsummaryshare::class),
            new ClassMap('CT_summarybds', Type\CTSummarybds::class),
            new ClassMap('CT_summaryich', Type\CTSummaryich::class),
            new ClassMap('CT_summaryindebt', Type\CTSummaryindebt::class),
            new ClassMap('CT_summarytpd', Type\CTSummarytpd::class),
            new ClassMap('CT_summaryaddress', Type\CTSummaryaddress::class),
            new ClassMap('CT_summaryresidency', Type\CTSummaryresidency::class),
            new ClassMap('CT_alertindividual', Type\CTAlertindividual::class),
            new ClassMap('CT_alert', Type\CTAlert::class),
            new ClassMap('CT_hho', Type\CTHho::class),
            new ClassMap('CT_outputthirdpartyalerts', Type\CTOutputthirdpartyalerts::class),
            new ClassMap('CT_addressconfresident', Type\CTAddressconfresident::class),
            new ClassMap('CT_supplierdetails', Type\CTSupplierdetails::class),
            new ClassMap('CT_outputaliaslink', Type\CTOutputaliaslink::class),
            new ClassMap('CT_outputassociatelink', Type\CTOutputassociatelink::class),
            new ClassMap('CT_outputnotice', Type\CTOutputnotice::class),
            new ClassMap('CT_outputapplicant', Type\CTOutputapplicant::class),
            new ClassMap('creditscores', Type\Creditscores::class),
            new ClassMap('addressconfs', Type\Addressconfs::class),
            new ClassMap('judgments', Type\Judgments::class),
            new ClassMap('bais', Type\Bais::class),
            new ClassMap('nocs', Type\Nocs::class),
            new ClassMap('searches', Type\Searches::class),
            new ClassMap('addresslinks', Type\Addresslinks::class),
            new ClassMap('aliaslinks', Type\Aliaslinks::class),
            new ClassMap('associatelinks', Type\Associatelinks::class),
            new ClassMap('cifas', Type\Cifas::class),
            new ClassMap('rtr', Type\Rtr::class),
            new ClassMap('accs', Type\Accs::class),
            new ClassMap('CT_creditreport', Type\CTCreditreport::class),
            new ClassMap('applicant', Type\Applicant::class),
            new ClassMap('oias', Type\Oias::class),
            new ClassMap('oia', Type\Oia::class),
            new ClassMap('CT_summaryrtr', Type\CTSummaryrtr::class),
            new ClassMap('CT_outputrtraccount', Type\CTOutputrtraccount::class),
            new ClassMap('holder', Type\Holder::class),
            new ClassMap('CT_SearchResponse', Type\CTSearchResponse::class),
            new ClassMap('CT_SearchResult', Type\CTSearchResult::class),
            new ClassMap('ChangePassword07a', Type\ChangePassword07a::class),
            new ClassMap('ChangePassword07aResponse', Type\ChangePassword07aResponse::class),
        ]);
    }


}

