<?php

namespace PaymentAssist;

use Soap\Encoding\ClassMap\ClassMapCollection;
use Soap\Encoding\ClassMap\ClassMap;

class CreditsafeClassmap
{
    public static function types() : \Soap\Encoding\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsidentity', Type\CTDemographicsidentity::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsperson', Type\CTDemographicsperson::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsaccommodation', Type\CTDemographicsaccommodation::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsemail', Type\CTDemographicsemail::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicstelephone', Type\CTDemographicstelephone::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsincome', Type\CTDemographicsincome::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsexpenditure', Type\CTDemographicsexpenditure::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsaccount', Type\CTDemographicsaccount::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsemployment', Type\CTDemographicsemployment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsincomedetails', Type\CTDemographicsincomedetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_applicantdemographics', Type\CTApplicantdemographics::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'contact', Type\Contact::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_address', Type\CTAddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddress', Type\CTInputaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputname', Type\CTInputname::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputamendment', Type\CTInputamendment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_amendsubsequent', Type\CTAmendsubsequent::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'amendments', Type\Amendments::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_searchapplicant', Type\CTSearchapplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_searchrequest', Type\CTSearchrequest::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatches', Type\CTInputaddressandmatches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'fullmatches', Type\Fullmatches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'fullmatch', Type\Fullmatch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'addressmatch', Type\Addressmatch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'name', Type\Name::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'namematches', Type\Namematches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'namematch', Type\Namematch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_picklistapplicant', Type\CTPicklistapplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_linkrequest', Type\CTLinkrequest::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_jobdetails', Type\CTJobdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_payload', Type\CTPayload::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_apipicklist', Type\CTApipicklist::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_Search', Type\CTSearch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SearchDefinition', Type\CTSearchDefinition::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SubsequentSearch', Type\CTSubsequentSearch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SubsequentSearchDefinition', Type\CTSubsequentSearchDefinition::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LinkSearch', Type\CTLinkSearch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LinkSearchDefinition', Type\CTLinkSearchDefinition::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LookupDataResponse', Type\CTLookupDataResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LookupDataResult', Type\CTLookupDataResult::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'table', Type\Table::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'row', Type\Row::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_TestResponse', Type\CTTestResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_TestResult', Type\CTTestResult::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddress', Type\CTOutputaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputerhistory', Type\CTOutputerhistory::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputscore', Type\CTOutputscore::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'score', Type\Score::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'reasons', Type\Reasons::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddressconf', Type\CTOutputaddressconf::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputjudgment', Type\CTOutputjudgment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputinsolvency', Type\CTOutputinsolvency::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'restriction', Type\Restriction::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputsearchhistory', Type\CTOutputsearchhistory::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputlinkaddresses', Type\CTOutputlinkaddresses::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputlinkaddress', Type\CTOutputlinkaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddresslinks', Type\CTOutputaddresslinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddresslink', Type\CTOutputaddresslink::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasfiling', Type\CTOutputcifasfiling::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'person', Type\Person::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'company', Type\Company::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'details', Type\Details::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasaddress', Type\CTOutputcifasaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifassubject', Type\CTOutputcifassubject::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'person', Type\Person::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'company', Type\Company::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascasedata', Type\CTOutputcifascasedata::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'filingreasons', Type\Filingreasons::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'subjects', Type\Subjects::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascase', Type\CTOutputcifascase::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'dmrs', Type\Dmrs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccount', Type\CTOutputshareaccount::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'supplierdetails', Type\Supplierdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'accholderdetails', Type\Accholderdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'default', Type\DefaultType::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'delinquent', Type\Delinquent::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'acchistory', Type\Acchistory::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'ah', Type\Ah::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'accdetails', Type\Accdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics', Type\CTOutputdemographics::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'family', Type\Family::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'household', Type\Household::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'age', Type\Age::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'economic', Type\Economic::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'economicactivity', Type\Economicactivity::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'socialclass', Type\Socialclass::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'housing', Type\Housing::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'propertyprice', Type\Propertyprice::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'movement', Type\Movement::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006', Type\CTOutputdemographics2006::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'age', Type\Age::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'tenure', Type\Tenure::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'hhcomp', Type\Hhcomp::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'economic', Type\Economic::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'lifestage', Type\Lifestage::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'social', Type\Social::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'occupation', Type\Occupation::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'mortgage', Type\Mortgage::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'sharehld', Type\Sharehld::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'unemployment', Type\Unemployment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'unemprate', Type\Unemprate::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'property', Type\Property::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'international', Type\International::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputsummaryblock', Type\CTOutputsummaryblock::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertsummary', Type\CTAlertsummary::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_hhosummary', Type\CTHhosummary::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarysearches', Type\CTSummarysearches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarybai', Type\CTSummarybai::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryjudgment', Type\CTSummaryjudgment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarynotices', Type\CTSummarynotices::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarylinks', Type\CTSummarylinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarycifas', Type\CTSummarycifas::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryshare', Type\CTSummaryshare::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertsummaryshare', Type\CTAlertsummaryshare::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarybds', Type\CTSummarybds::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryich', Type\CTSummaryich::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryindebt', Type\CTSummaryindebt::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarytpd', Type\CTSummarytpd::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryaddress', Type\CTSummaryaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryresidency', Type\CTSummaryresidency::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertindividual', Type\CTAlertindividual::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alert', Type\CTAlert::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'creditscores', Type\Creditscores::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_hho', Type\CTHho::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'creditscores', Type\Creditscores::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputthirdpartyalerts', Type\CTOutputthirdpartyalerts::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_addressconfresident', Type\CTAddressconfresident::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_supplierdetails', Type\CTSupplierdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaliaslink', Type\CTOutputaliaslink::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputassociatelink', Type\CTOutputassociatelink::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputnotice', Type\CTOutputnotice::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicant', Type\CTOutputapplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'creditscores', Type\Creditscores::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'addressconfs', Type\Addressconfs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'judgments', Type\Judgments::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'bais', Type\Bais::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'nocs', Type\Nocs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'searches', Type\Searches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'addresslinks', Type\Addresslinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'aliaslinks', Type\Aliaslinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'associatelinks', Type\Associatelinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'cifas', Type\Cifas::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'rtr', Type\Rtr::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'accs', Type\Accs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_creditreport', Type\CTCreditreport::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'applicant', Type\Applicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'oias', Type\Oias::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'oia', Type\Oia::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryrtr', Type\CTSummaryrtr::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputrtraccount', Type\CTOutputrtraccount::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'holder', Type\Holder::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SearchResponse', Type\CTSearchResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SearchResult', Type\CTSearchResult::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'callcreditheaders', Type\Callcreditheaders::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'Search07a', Type\Search07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'Search07aResponse', Type\Search07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AddressLinkSearch07a', Type\AddressLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AddressLinkSearch07aResponse', Type\AddressLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AssociateLinkSearch07a', Type\AssociateLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AssociateLinkSearch07aResponse', Type\AssociateLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentSearch07a', Type\SubsequentSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentSearch07aResponse', Type\SubsequentSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAddressLinkSearch07a', Type\SubsequentAddressLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAddressLinkSearch07aResponse', Type\SubsequentAddressLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAssociateLinkSearch07a', Type\SubsequentAssociateLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAssociateLinkSearch07aResponse', Type\SubsequentAssociateLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'ChangePassword07a', Type\ChangePassword07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'ChangePassword07aResponse', Type\ChangePassword07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'LookupData07aResponse', Type\LookupData07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'Test07aResponse', Type\Test07aResponse::class),
        );
    }

    public static function enums() : \Soap\Encoding\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(

        );
    }
}

