<?php

namespace PaymentAssist;

use PaymentAssist\Type;
use Soap\Encoding\ClassMap\ClassMapCollection;
use Soap\Encoding\ClassMap\ClassMap;

class CreditsafeClassmap
{
    public static function types(): \Soap\Encoding\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsidentity', Type\CTDemographicsidentity::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsperson', Type\CTDemographicsperson::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsaccommodation', Type\CTDemographicsaccommodation::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsemail', Type\CTDemographicsemail::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicstelephone', Type\CTDemographicstelephone::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsincome', Type\CTDemographicsincome::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsexpenditure', Type\CTDemographicsexpenditure::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsaccount', Type\CTDemographicsaccount::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsemployment', Type\CTDemographicsemployment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_demographicsincomedetails', Type\CTDemographicsincomedetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_applicantdemographics', Type\CTApplicantdemographics::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_applicantdemographicsContact', Type\CTApplicantdemographicsContact::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_address', Type\CTAddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddress', Type\CTInputaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputname', Type\CTInputname::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputamendment', Type\CTInputamendment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_amendsubsequent', Type\CTAmendsubsequent::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_amendsubsequentAmendments', Type\CTAmendsubsequentAmendments::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_searchapplicant', Type\CTSearchapplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_searchrequest', Type\CTSearchrequest::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatches', Type\CTInputaddressandmatches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatchesFullmatches', Type\CTInputaddressandmatchesFullmatches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatchesFullmatch', Type\CTInputaddressandmatchesFullmatch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatchesAddressmatch', Type\CTInputaddressandmatchesAddressmatch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatchesName', Type\CTInputaddressandmatchesName::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatchesNamematches', Type\CTInputaddressandmatchesNamematches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_inputaddressandmatchesNamematch', Type\CTInputaddressandmatchesNamematch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_picklistapplicant', Type\CTPicklistapplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_linkrequest', Type\CTLinkrequest::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_jobdetails', Type\CTJobdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_payload', Type\CTPayload::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_apipicklist', Type\CTApipicklist::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_Search', Type\CTSearch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SearchDefinition', Type\CTSearchDefinition::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SubsequentSearch', Type\CTSubsequentSearch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SubsequentSearchDefinition', Type\CTSubsequentSearchDefinition::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LinkSearch', Type\CTLinkSearch::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LinkSearchDefinition', Type\CTLinkSearchDefinition::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LookupDataResponse', Type\CTLookupDataResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LookupDataResult', Type\CTLookupDataResult::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LookupDataResultTable', Type\CTLookupDataResultTable::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_LookupDataResultRow', Type\CTLookupDataResultRow::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_TestResponse', Type\CTTestResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_TestResult', Type\CTTestResult::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddress', Type\CTOutputaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputerhistory', Type\CTOutputerhistory::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputscore', Type\CTOutputscore::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputscoreScore', Type\CTOutputscoreScore::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputscoreReasons', Type\CTOutputscoreReasons::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddressconf', Type\CTOutputaddressconf::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputjudgment', Type\CTOutputjudgment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputinsolvency', Type\CTOutputinsolvency::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputinsolvencyRestriction', Type\CTOutputinsolvencyRestriction::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputsearchhistory', Type\CTOutputsearchhistory::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputlinkaddresses', Type\CTOutputlinkaddresses::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputlinkaddress', Type\CTOutputlinkaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddresslinks', Type\CTOutputaddresslinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaddresslink', Type\CTOutputaddresslink::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasfiling', Type\CTOutputcifasfiling::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasfilingPerson', Type\CTOutputcifasfilingPerson::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasfilingCompany', Type\CTOutputcifasfilingCompany::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasfilingDetails', Type\CTOutputcifasfilingDetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifasaddress', Type\CTOutputcifasaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifassubject', Type\CTOutputcifassubject::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifassubjectPerson', Type\CTOutputcifassubjectPerson::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifassubjectCompany', Type\CTOutputcifassubjectCompany::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascasedata', Type\CTOutputcifascasedata::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascasedataFilingreasons', Type\CTOutputcifascasedataFilingreasons::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascasedataSubjects', Type\CTOutputcifascasedataSubjects::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascase', Type\CTOutputcifascase::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputcifascaseDmrs', Type\CTOutputcifascaseDmrs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccount', Type\CTOutputshareaccount::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountSupplierdetails', Type\CTOutputshareaccountSupplierdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountAccholderdetails', Type\CTOutputshareaccountAccholderdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountDefault', Type\CTOutputshareaccountDefault::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountDelinquent', Type\CTOutputshareaccountDelinquent::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountAcchistory', Type\CTOutputshareaccountAcchistory::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountAh', Type\CTOutputshareaccountAh::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputshareaccountAccdetails', Type\CTOutputshareaccountAccdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics', Type\CTOutputdemographics::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsFamily', Type\CTOutputdemographicsFamily::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsHousehold', Type\CTOutputdemographicsHousehold::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsAge', Type\CTOutputdemographicsAge::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsEconomic', Type\CTOutputdemographicsEconomic::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsEconomicactivity', Type\CTOutputdemographicsEconomicactivity::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsSocialclass', Type\CTOutputdemographicsSocialclass::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsHousing', Type\CTOutputdemographicsHousing::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsPropertyprice', Type\CTOutputdemographicsPropertyprice::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographicsMovement', Type\CTOutputdemographicsMovement::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006', Type\CTOutputdemographics2006::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Age', Type\CTOutputdemographics2006Age::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Tenure', Type\CTOutputdemographics2006Tenure::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Hhcomp', Type\CTOutputdemographics2006Hhcomp::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Economic', Type\CTOutputdemographics2006Economic::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Lifestage', Type\CTOutputdemographics2006Lifestage::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Social', Type\CTOutputdemographics2006Social::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Occupation', Type\CTOutputdemographics2006Occupation::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Mortgage', Type\CTOutputdemographics2006Mortgage::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Sharehld', Type\CTOutputdemographics2006Sharehld::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Unemployment', Type\CTOutputdemographics2006Unemployment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Unemprate', Type\CTOutputdemographics2006Unemprate::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006Property', Type\CTOutputdemographics2006Property::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputdemographics2006International', Type\CTOutputdemographics2006International::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputsummaryblock', Type\CTOutputsummaryblock::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertsummary', Type\CTAlertsummary::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_hhosummary', Type\CTHhosummary::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarysearches', Type\CTSummarysearches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarybai', Type\CTSummarybai::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryjudgment', Type\CTSummaryjudgment::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarynotices', Type\CTSummarynotices::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarylinks', Type\CTSummarylinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarycifas', Type\CTSummarycifas::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryshare', Type\CTSummaryshare::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertsummaryshare', Type\CTAlertsummaryshare::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarybds', Type\CTSummarybds::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryich', Type\CTSummaryich::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryindebt', Type\CTSummaryindebt::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summarytpd', Type\CTSummarytpd::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryaddress', Type\CTSummaryaddress::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryresidency', Type\CTSummaryresidency::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertindividual', Type\CTAlertindividual::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alert', Type\CTAlert::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_alertCreditscores', Type\CTAlertCreditscores::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_hho', Type\CTHho::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_hhoCreditscores', Type\CTHhoCreditscores::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputthirdpartyalerts', Type\CTOutputthirdpartyalerts::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_addressconfresident', Type\CTAddressconfresident::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_supplierdetails', Type\CTSupplierdetails::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputaliaslink', Type\CTOutputaliaslink::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputassociatelink', Type\CTOutputassociatelink::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputnotice', Type\CTOutputnotice::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicant', Type\CTOutputapplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantCreditscores', Type\CTOutputapplicantCreditscores::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantAddressconfs', Type\CTOutputapplicantAddressconfs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantJudgments', Type\CTOutputapplicantJudgments::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantBais', Type\CTOutputapplicantBais::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantNocs', Type\CTOutputapplicantNocs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantSearches', Type\CTOutputapplicantSearches::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantAddresslinks', Type\CTOutputapplicantAddresslinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantAliaslinks', Type\CTOutputapplicantAliaslinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantAssociatelinks', Type\CTOutputapplicantAssociatelinks::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantCifas', Type\CTOutputapplicantCifas::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantRtr', Type\CTOutputapplicantRtr::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputapplicantAccs', Type\CTOutputapplicantAccs::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_creditreport', Type\CTCreditreport::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_creditreportApplicant', Type\CTCreditreportApplicant::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_creditreportOias', Type\CTCreditreportOias::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_creditreportOia', Type\CTCreditreportOia::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_summaryrtr', Type\CTSummaryrtr::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputrtraccount', Type\CTOutputrtraccount::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_outputrtraccountHolder', Type\CTOutputrtraccountHolder::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SearchResponse', Type\CTSearchResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'CT_SearchResult', Type\CTSearchResult::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'callcreditheaders', Type\Callcreditheaders::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'Search07a', Type\Search07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'Search07aResponse', Type\Search07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AddressLinkSearch07a', Type\AddressLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AddressLinkSearch07aResponse', Type\AddressLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AssociateLinkSearch07a', Type\AssociateLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'AssociateLinkSearch07aResponse', Type\AssociateLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentSearch07a', Type\SubsequentSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentSearch07aResponse', Type\SubsequentSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAddressLinkSearch07a', Type\SubsequentAddressLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAddressLinkSearch07aResponse', Type\SubsequentAddressLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAssociateLinkSearch07a', Type\SubsequentAssociateLinkSearch07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'SubsequentAssociateLinkSearch07aResponse', Type\SubsequentAssociateLinkSearch07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'ChangePassword07a', Type\ChangePassword07a::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'ChangePassword07aResponse', Type\ChangePassword07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'LookupData07aResponse', Type\LookupData07aResponse::class),
            new ClassMap('urn:callcredit.co.uk/soap:callreport7', 'Test07aResponse', Type\Test07aResponse::class),
        );
    }

    public static function enums(): \Soap\Encoding\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(

        );
    }
}

